micronaut:
  application:
    name: liberty
  router:
    static-resources:
      files:
        paths: classpath:public
        mapping: /**
        enabled: true
  security:
    enabled: true
    intercept-url-map:
      - pattern: /
        access:
          - isAnonymous()
      - pattern: /git/**
        access:
          - isAnonymous()
      - pattern: /cloud/**
        access:
          - isAuthenticated()
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop